Phobos/Phobos/Areas/admin/Controllers/GalleriesManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using CivilianJobs.Models;
using System.IO;
using System.Text.RegularExpressions;


namespace CivilianJobs.Areas.admin.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class GalleriesManagerController : CivilianJobsAdminController
    {
        private string ImageFilePath = @"~/Content/upload/modules/galleries/";
        
        //
        // GET: /admin/GalleriesManager/

        public ActionResult Index()
        {
            return View(db.Galleries.ToList().OrderBy(e => e.Name));
        }

       
        //
        // GET: /admin/GalleriesManager/Create
        public ActionResult Create(int id = 0)
        {
            Gallery gallery = new Gallery();
            return View();
        }

        //
        // POST: /admin/GalleriesManager/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Gallery gallery)
        {
            if (ModelState.IsValid)
            {
                if (!db.Galleries.Any(e => e.SEOURL == gallery.SEOURL))
                {
                    gallery.Created = DateTime.Now;
                    db.Galleries.Add(gallery);
                    db.SaveChanges();
                    return RedirectToAction("Edit", new { id = gallery.GalleryID});
                }
                else
                {
                    ModelState.AddModelError("SEOURL", "This path is already taken");
                }
            }
            return View(gallery);
        }

        //
        // GET: /admin/GalleriesManager/Edit/5
        public ActionResult Edit(int id = 0)
        {
            Gallery gallery = db.Galleries.Find(id);
            if (gallery == null) return Http404();
            return View(gallery);
        }

        //
        // POST: /admin/GalleriesManager/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Gallery gallery)
        {
            if (ModelState.IsValid)
            {
                if (!db.Galleries.Any(e => e.SEOURL == gallery.SEOURL && e.GalleryID != gallery.GalleryID))
                {
                    db.Entry(gallery).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("SEOURL", "This path is already taken");
                }
            }
            return View(gallery);
        }

        //
        // GET: /admin/GalleriesManager/Delete/5
        public ActionResult Delete(int id = 0)
        {
            Gallery gallery = db.Galleries.Find(id);
            if (gallery == null) return Http404();
            return View(gallery);
        }

        //
        // POST: /admin/GalleriesManager/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gallery gallery = db.Galleries.Find(id);
            if (gallery == null) return Http404();

            //delete image files
            DeleteItemImages(id);

            //delete directory
            if(gallery.GalleryItems != null && gallery.GalleryItems.Count > 0)
            {
                GalleryItem firstItem = gallery.GalleryItems.FirstOrDefault();
                if (firstItem.ImageUrl != null && firstItem.ImageUrl != "")
                {
                    DirectoryInfo di = new FileInfo(System.IO.Path.Combine(Server.MapPath(firstItem.ImageUrl))).Directory;
                    if (di.Exists) di.Delete();
                }
            }

            //delete gallery and its items
            gallery.DeleteSafe(db);
            
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        //
        // GET: /admin/GalleriesManager/Items
        public ActionResult Items(int id = 0)
        {
            Gallery gallery = db.Galleries.Find(id);
            if (gallery == null) return Http404();
            return View(gallery);
        }


        //
        // GET: /admin/GalleriesManager/CreateItem
        public ActionResult CreateItem(int id = 0)
        {
            GalleryItem galitem = new GalleryItem { GalleryID = id };
            return View(galitem);
        }

        //
        // POST: /admin/GalleriesManager/CreateItem
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateItem(GalleryItem galitem, HttpPostedFileBase ItemImage)
        {
            if (ModelState.IsValid)
            {
                db.GalleryItems.Add(galitem);
                db.SaveChanges();

                if (ItemImage != null && ItemImage.ContentLength > 0)
                {
                    try
                    {
                        string filename = Path.GetFileName(ItemImage.FileName);
                        filename = galitem.GalleryItemID + "_" + Regex.Replace(filename, @"[^a-zA-Z0-9\.-]", "_");
                        string directory = ImageFilePath + galitem.GalleryID.ToString() + @"/";
                        string path = System.IO.Path.Combine(Server.MapPath(directory), filename);
                        FileInfo fi = new FileInfo(path);
                        fi.Directory.Create(); // If the directory already exists, this method does nothing.
                        if (fi.Exists) fi.Delete();
                        ItemImage.SaveAs(path);
                        galitem.ImageUrl = directory.Replace("~", "") + filename;
                        db.Entry(galitem).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    catch (Exception)
                    {
                        AlertHandler.AddAlert("Error uploading image!", UserAlertLevel.ERROR);
                    }
                }

                return RedirectToAction("Items", new { id = galitem.GalleryID });
            }

            return View(galitem);
        }

        //
        // GET: /admin/GalleriesManager/EditItem/5
        public ActionResult EditItem(int id = 0)
        {
            GalleryItem galitem = db.GalleryItems.Find(id);
            if (galitem == null) return Http404();
            return View(galitem);
        }

        //
        // POST: /admin/GalleriesManager/EditItem/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditItem(GalleryItem galitem, HttpPostedFileBase ItemImage)
        {
            if (ModelState.IsValid)
            {
                if (ItemImage != null && ItemImage.ContentLength > 0)
                {
                    try {
                        //delete old img
                        string deletefileName = Path.GetFileName(Request.Form["OldImage"]);
                        string deletefileDirectory = ImageFilePath + galitem.GalleryID.ToString() + @"/";
                        string deletefilePath = System.IO.Path.Combine(Server.MapPath(deletefileDirectory), deletefileName);
                        FileInfo deletefileInfo = new FileInfo(deletefilePath);
                        if (deletefileInfo.Exists) deletefileInfo.Delete();

                        //save new img
                        string filename = Path.GetFileName(ItemImage.FileName);
                        filename = galitem.GalleryItemID + "_" + Regex.Replace(filename, @"[^a-zA-Z0-9\.-]", "_");
                        string directory = ImageFilePath + galitem.GalleryID.ToString() + @"/";
                        string path = System.IO.Path.Combine(Server.MapPath(directory), filename);
                        FileInfo fi = new FileInfo(path);
                        fi.Directory.Create(); // If the directory already exists, this method does nothing.
                        if (fi.Exists) fi.Delete();
                        ItemImage.SaveAs(path);
                        galitem.ImageUrl = directory.Replace("~","") + filename;
                    }
                    catch (Exception err)
                    {
                        ViewBag.Message = "Error uploading file";
                        throw new Exception(err.Message);
                    }
                }

                db.Entry(galitem).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Items", new { id = galitem.GalleryID });
            }
            return View(galitem);
        }

        //
        // GET: /admin/GalleriesManager/DeleteItem/5
        public ActionResult DeleteItem(int id = 0)
        {
            GalleryItem galitem = db.GalleryItems.Find(id);
            if (galitem == null) return Http404();
            return View(galitem);
        }

        //
        // POST: /admin/GalleriesManager/DeleteItem/5

        [HttpPost, ActionName("DeleteItem")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmedItem(int id)
        {
            GalleryItem galitem = db.GalleryItems.Find(id);

            if (galitem.ImageUrl != null && galitem.ImageUrl.Trim() != "")
            {
                string path = System.IO.Path.Combine(Server.MapPath(galitem.ImageUrl));
                FileInfo fi = new FileInfo(path);
                if (fi.Exists) fi.Delete();
            }

            db.GalleryItems.Remove(galitem);
            db.SaveChanges();

            return RedirectToAction("Items", new { id = galitem.GalleryID });
        }


        private void DeleteItemImages(int id)
        {
            Gallery gallery = db.Galleries.Find(id);
            foreach (GalleryItem galitem in gallery.GalleryItems)
            {
                if (galitem.ImageUrl != null && galitem.ImageUrl.Trim() != "")
                {

Phobos/Phobos/Areas/admin/Views/GalleriesManager/Create.cshtml
@model CivilianJobs.Models.Gallery

@{
    ViewBag.Title = "Create Gallery";
}

<div class="span12 pad-left pad-right admin">

    <h2>@ViewBag.Title</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <table class="table table-bordered">
            <tr>
                <th colspan="4" class="text-right">
                    <div class="btn-group">
                        <input type="submit" value="Save" class="btn btn-primary"/>
                        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </th>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Name)
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </td>
                <td>
                    @Html.LabelFor(model => model.SEOURL)
                    @Html.EditorFor(model => model.SEOURL)
                    @Html.ValidationMessageFor(model => model.SEOURL)
                </td>
                
            </tr>
            <tr>
                <td colspan="4">
                    @Html.LabelFor(model => model.Description)
                    @Html.TextAreaFor(model => model.Description, new { @class = "wysiwygsmall" })
                    @Html.ValidationMessageFor(model => model.Description)
                </td>
            </tr>

        </table>
    }

</div>

Phobos/Phobos/Areas/admin/Views/GalleriesManager/CreateItem.cshtml
@model CivilianJobs.Models.GalleryItem

@{
    ViewBag.Title = "Create Item";
}

<div class="span12 pad-left pad-right admin">

    <h2>@ViewBag.Title</h2>

    @using (Html.BeginForm(Html.BeginForm("CreateItem", "GalleriesManager", FormMethod.Post, new { enctype = "multipart/form-data" })))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.GalleryID)

        
        <table class="table table-bordered">
           
            <tr>
                <th colspan="4" class="text-right">
                    <div class="btn-group">
                        <input type="submit" value="Save" class="btn btn-primary"/>
                        @Html.ActionLink("Cancel", "Items", "GalleriesManager", new { id = Model.GalleryID }, new { @class = "btn btn-primary" })
                    </div>
                </th>
            </tr>
        
            <tr>
                
                <td>
                    @Html.LabelFor(model => model.Title)
                    @Html.EditorFor(model => model.Title)
                    @Html.ValidationMessageFor(model => model.Title)
                </td>
                <td>
                    @Html.LabelFor(model => model.Order)
                    @Html.EditorFor(model => model.Order)
                    @Html.ValidationMessageFor(model => model.Order)
                </td>
                <td>
                    @Html.LabelFor(model => model.Active)
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active)
                </td> 
            </tr>
            <tr>
                <td colspan="3">
                    @Html.LabelFor(model => model.ImageUrl)
                    <input type="file" name="ItemImage" />
                    <br />
                    @Html.TextBoxFor(model => model.ImageUrl, new { @readonly = "readonly"})
                    @Html.ValidationMessageFor(model => model.ImageUrl)
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    @Html.LabelFor(model => model.Description)
                    @Html.TextAreaFor(model => model.Description, new { @class = "wysiwygsmall" })
                    @Html.ValidationMessageFor(model => model.Description)
                </td>
            </tr>
            
        </table>
    }

</div>
@section Scripts{
    <script type="text/javascript">
        $(function(){
            $("[name=ItemImage]").change(function (){
                $("#ImageUrl").val($(this).val());
             });
        });
    </script>
}

Phobos/Phobos/Areas/admin/Views/GalleriesManager/Delete.cshtml
@model CivilianJobs.Models.Gallery

@{
    ViewBag.Title = "Delete " + Model.Name;
}

<div class="span12 pad-left pad-right admin">

    <h2>@ViewBag.Title</h2>


 
    <h3>Are you sure you want to delete this gallery?</h3>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        <p>
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn" })
        </p>
    }


</div>

Phobos/Phobos/Areas/admin/Views/GalleriesManager/DeleteItem.cshtml
@model CivilianJobs.Models.GalleryItem

@{
    ViewBag.Title = "Delete " + Model.Title;
}

<div class="span12 pad-left pad-right admin">

    <h2>@ViewBag.Title</h2>

    <h3>Are you sure you want to delete this item?</h3>
    <p>
        <img src="@Model.ImageUrl" height="300" />
    </p>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        <p>
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Back to List", "Items", "GalleriesManager", new { id = Model.GalleryID }, new { @class = "btn" })
                            
        </p>
    }

</div>

Phobos/Phobos/Areas/admin/Views/GalleriesManager/Edit.cshtml
@model CivilianJobs.Models.Gallery

@{
    ViewBag.Title = "Edit " + Model.Name;
}

<div class="span12 pad-left pad-right admin">

    <h2>@ViewBag.Title</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <table class="table table-bordered">
            @Html.HiddenFor(model => model.GalleryID)
            @Html.HiddenFor(model => model.Created)
            <tr>
                <th colspan="4" class="text-right">
                    <div class="btn-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Edit Items", "Items", new { id = Model.GalleryID }, new { @class = "btn btn-primary" })
                    </div>
                </th>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Name)
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </td>
                <td>
                    @Html.LabelFor(model => model.SEOURL)
                    @Html.EditorFor(model => model.SEOURL)
                    @Html.ValidationMessageFor(model => model.SEOURL)
                </td>
                
            </tr>
            <tr>
                <td colspan="4">
                    @Html.LabelFor(model => model.Description)
                    @Html.TextAreaFor(model => model.Description, new { @class = "wysiwygsmall" })
                    @Html.ValidationMessageFor(model => model.Description)
                </td>
            </tr>

        </table>
    }

</div>

Phobos/Phobos/Areas/admin/Views/GalleriesManager/EditItem.cshtml
@model CivilianJobs.Models.GalleryItem

@{
    ViewBag.Title = "Edit " + Model.Title;
}

<div class="span12 pad-left pad-right admin">

    <h2>@ViewBag.Title</h2>

    @using (Html.BeginForm(Html.BeginForm("EditItem", "GalleriesManager", FormMethod.Post, new { enctype = "multipart/form-data" })))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.GalleryItemID)
        @Html.HiddenFor(model => model.GalleryID)

        
        <table class="table table-bordered">
           
            <tr>
                <th colspan="4" class="text-right">
                    <div class="btn-group">
                        <input type="submit" value="Save" class="btn btn-primary"/>
                     @Html.ActionLink("Cancel", "Items", "GalleriesManager", new { id = Model.GalleryID }, new { @class = "btn btn-primary" })
                    </div>
                </th>
            </tr>
        
            <tr>
                
                <td>
                    @Html.LabelFor(model => model.Title)
                    @Html.EditorFor(model => model.Title)
                    @Html.ValidationMessageFor(model => model.Title)
                </td>
                <td>
                    @Html.LabelFor(model => model.Order)
                    @Html.EditorFor(model => model.Order)
                    @Html.ValidationMessageFor(model => model.Order)
                </td>
                <td>
                    @Html.LabelFor(model => model.Active)
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active)
                </td> 
            </tr>
            <tr>
                <td colspan="3">
                    @Html.LabelFor(model => model.ImageUrl)
                    <input type="file" name="ItemImage" />
                    <br />
                    @Html.TextBoxFor(model => model.ImageUrl, new { @readonly = "readonly"})
                    @Html.Hidden("OldImage", Model.ImageUrl)
                    
                    @if (Model.ImageUrl != null && Model.ImageUrl != "")
                    {
                        <br /><br /><img  src="@Model.ImageUrl" />
                    }
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    @Html.LabelFor(model => model.Description)
                    @Html.TextAreaFor(model => model.Description, new { @class = "wysiwygsmall" })
                    @Html.ValidationMessageFor(model => model.Description)
                </td>
            </tr>
            
        </table>
    }

</div>
@section Scripts{
    <script type="text/javascript">
        $(function(){
            $("[name=ItemImage]").change(function (){
                $("#ImageUrl").val($(this).val());
             });
        });
    </script>
}

Phobos/Phobos/Areas/admin/Views/GalleriesManager/Index.cshtml
@model IEnumerable<CivilianJobs.Models.Gallery>

@{
    ViewBag.Title = "Galleries";
}

<div class="span12 pad-left pad-right admin">

    <h2>@ViewBag.Title</h2>

    <div class="btn-group">
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
    </div>
    <br /><br />
    <table class="table table-striped table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>        
            <th class="options"></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>        

            <td>
                <div class="btn-group">
                    @Html.ActionLink("Edit", "Edit", new { id = item.GalleryID }, new { @class = "btn btn-primary" })
                    @Html.ActionLink("Items", "Items", new { id = item.GalleryID }, new { @class = "btn btn-primary" })
                    @Html.ActionLink("Delete", "Delete", new { id=item.GalleryID }, new { @class = "btn btn-danger" })
                </div>
            </td>
        </tr>
    }

    </table>

</div>

Phobos/Phobos/Areas/admin/Views/GalleriesManager/Items.cshtml
@model CivilianJobs.Models.Gallery

@{
    ViewBag.Title = "Edit Items For " + Model.Name;
}

<div class="span12 pad-left pad-right admin">

    <h2>@ViewBag.Title</h2>

    <p>
        <div class="btn-group">
        @Html.ActionLink("Create New Item", "CreateItem", new { id = Model.GalleryID }, new { @class = "btn btn-primary" })
        @Html.ActionLink("Edit Gallery", "Edit", "GalleriesManager", new { id = Model.GalleryID }, new { @class = "btn btn-primary" })
        @Html.ActionLink("Back to Galleries List", "Index", "GalleriesManager", null, new { @class = "btn btn-primary" })
        </div>
    </p>
    <table class="table table-striped table-bordered">
        <tr>
            <th>Order</th>
            <th>Image</th>
            <th></th>
        </tr>

    @foreach (var item in Model.GalleryItems) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Order)
            </td>
            <td>
                <img src="@Html.DisplayFor(modelItem => item.ImageUrl)" height="100" />
            </td>
            <td>
                <div class="btn-group">
                    @Html.ActionLink("Edit", "EditItem", new { id = item.GalleryItemID }, new { @class = "btn btn-primary" })
                    @Html.ActionLink("Delete", "DeleteItem", new { id = item.GalleryItemID }, new { @class = "btn btn-danger" })
                </div>
            </td>
        </tr>
    }

    </table>

</div>