Phobos/Phobos/Areas/admin/Controllers/AdManagerController.cs
using CivilianJobs.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace CivilianJobs.Areas.admin.Controllers
{
    public class AdManagerController : CivilianJobsAdminController
    {
        private string ImageFilePath = @"~/Content/upload/ad/";
        //
        // GET: /admin/AdManager/

        public ActionResult Index()
        {
            var ads = db.Ads;
            return View(ads.ToList().OrderBy(a => a.AdID));
        }

        //
        // GET: /admin/AdManager/Edit/5

        public ActionResult View(int id = 0)
        {
            Ad ad = db.Ads.Find(id);
            if (ad == null)
            {
                return Http404();
            }
            return View(ad);
        }

        //
        // GET: /admin/AdManager/Create

        public ActionResult Create(int id = 0)
        {
            Ad a = new Ad();
            return View(a);
        }

        //
        // POST: /admin/AdManager/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Ad ad, HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                if (!db.Ads.Any(e => e.PublishFor == ad.PublishFor && e.PublishPage == ad.PublishPage))
                {
                    ad.PublishStartDate = DateTime.Now;
                    ad.CreateDate = DateTime.Now;
                    ad.UpdateDate = DateTime.Now;
                    db.Ads.Add(ad);
                    db.SaveChanges();

                    if (Image != null && Image.ContentLength > 0)
                    {
                        try
                        {
                            string filename = Path.GetFileName(Image.FileName);
                            filename = ad.AdID + "_" + Regex.Replace(filename, @"[^a-zA-Z0-9\.-]", "_");
                            string directory = ImageFilePath + ad.AdID.ToString() + @"/";
                            string path = System.IO.Path.Combine(Server.MapPath(directory), filename);
                            FileInfo fi = new FileInfo(path);
                            fi.Directory.Create(); // If the directory already exists, this method does nothing.
                            if (fi.Exists) fi.Delete();
                            Image.SaveAs(path);
                            ad.ImageUrl = directory.Replace("~", "") + filename;
                            db.Entry(ad).State = System.Data.Entity.EntityState.Modified;
                            db.SaveChanges();
                        }
                        catch (Exception)
                        {
                            AlertHandler.AddAlert("Error uploading image!", UserAlertLevel.ERROR);
                            ViewBag.UserAlerts = "Error uploading image!";
                        }
                    }

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("SEOURL", "This ad is already taken");
                    ViewBag.UserAlerts = "This ad is already taken";
                }
            }
            return View(ad);
        }

        //
        // GET: /admin/AdManager/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Ad ad = db.Ads.Find(id);
            if (ad == null)
            {
                return Http404();
            }
            return View(ad);
        }

        //
        // POST: /admin/AdManager/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Ad ad, HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                //if (!db.Ads.Any(e => e.PublishTo == ad.PublishTo))
                //{
                    ad.UpdateDate = DateTime.Now;
                    db.Entry(ad).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();

                    if (Image != null && Image.ContentLength > 0)
                    {
                        try
                        {
                            string filename = Path.GetFileName(Image.FileName);
                            filename = ad.AdID + "_" + Regex.Replace(filename, @"[^a-zA-Z0-9\.-]", "_");
                            string directory = ImageFilePath + ad.AdID.ToString() + @"/";
                            string path = System.IO.Path.Combine(Server.MapPath(directory), filename);
                            FileInfo fi = new FileInfo(path);
                            fi.Directory.Create(); // If the directory already exists, this method does nothing.
                            if (fi.Exists) fi.Delete();
                            Image.SaveAs(path);
                            ad.ImageUrl = directory.Replace("~", "") + filename;
                            db.Entry(ad).State = System.Data.Entity.EntityState.Modified;
                            db.SaveChanges();
                        }
                        catch (Exception)
                        {
                            AlertHandler.AddAlert("Error uploading image!", UserAlertLevel.ERROR);
                            ViewBag.UserAlerts = "Error uploading image!";
                        }
                    }

                    return RedirectToAction("Index");
                //}
                //else
                //{
                //    ModelState.AddModelError("SEOURL", "This add is already taken");
                //}
            }
            return View(ad);
        }

        //
        // GET: /admin/AdManager/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Ad ad = db.Ads.Find(id);
            if (ad == null)
            {
                return Http404();
            }
            return View(ad);
        }

        //
        // POST: /admin/AdManager/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int AdID)
        {
            Ad ad = db.Ads.FirstOrDefault(a => a.AdID == AdID);
            if (ad == null) return Http404();
            db.Ads.Remove(ad);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Phobos/Phobos/Areas/admin/Views/AdManager/Create.cshtml
@model CivilianJobs.Models.Ad
@{
    ViewBag.Title = "Create Ad";
}
<style>
    iframe {
        max-height: 125px;
    }
</style>
<div class="span12 pad-left pad-right admin">
    <h5 class="alert-danger">@ViewBag.UserAlerts</h5>
    <h2>@ViewBag.Title</h2>
    @using (Html.BeginForm("Create", "AdManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.AdID)
        <table class="table table-bordered">
            <tr>
                <th colspan="1">
                    <div class="btn-group">
                        <a onclick="submitForm()" class="btn btn-primary" href="javascript:void(0)">Save</a>
                        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </th>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Title, new { @style = "display: inline-block;" })
                    <label class="labelInfo"><img src="~/Content/img/info.png" /> Will be dispalyed under Ad </label>
                    <br />
                    @Html.EditorFor(model => model.Title, new { @class = "form-control"})
                    @Html.ValidationMessageFor(model => model.Title)
                </td>
                <td>
                    @Html.LabelFor(model => model.Hyperlink, new { @style = "display: inline-block;" })
                    <label class="labelInfo"><img src="~/Content/img/info.png" /> Url for Ad </label>
                    <br />
                    @Html.EditorFor(model => model.Hyperlink, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Hyperlink)
                </td>
                <td>
                    <label for="Hyperlink" style="display: inline-block;">Static Pages</label>
                    <label class="labelInfo"><img src="/Content/img/info.png"> List of static pages to post ad </label>
                    <br>
                    <div class="col-sm-11">
                        <select id="staticpage" class="form-control">
                            <option value="http://stage11.atomicdesign.net/page/employers">http://stage11.atomicdesign.net/page/employers</option>
                            <option value="http://stage11.atomicdesign.net/page/microsites">http://stage11.atomicdesign.net/page/microsites</option>
                            <option value="http://stage11.atomicdesign.net/page/military-job-fairs">http://stage11.atomicdesign.net/page/military-job-fairs</option>
                            <option value="http://stage11.atomicdesign.net/page/privacy-policy">http://stage11.atomicdesign.net/page/privacy-policy</option>
                            <option value="http://stage11.atomicdesign.net/staffing-products">http://stage11.atomicdesign.net/staffing-products</option>
                            <option value="http://stage11.atomicdesign.net/jobseeker/index">http://stage11.atomicdesign.net/jobseeker/index</option>
                            <option value="http://stage11.atomicdesign.net/page/about-us">http://stage11.atomicdesign.net/page/about-us</option>
                        </select>
                    </div>
                    <div class="col-sm-1">
                        <a href="javascript:void(0)"><i style="margin-top: 7px" class="glyphicon glyphicon-plus" onclick="addStaticPage()"></i></a>
                    </div>
                </td>
                
                <td>
                    @Html.LabelFor(model => model.Subject, new { @style = "display: inline-block;" })
                    <label class="labelInfo"><img src="~/Content/img/info.png" /> Subject for email notification </label>
                    <br />
                    @Html.EditorFor(model => model.Subject)
                    @Html.ValidationMessageFor(model => model.Subject)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.PublishFor, new { @style = "display: inline-block;" })
                    <label class="labelInfo"><img src="~/Content/img/info.png" /> Account where Ad will be displayed. @*If left empty, it will display for every Publish Page url*@ </label>
                    <br />
                    @Html.EditorFor(model => model.PublishFor)
                    @Html.ValidationMessageFor(model => model.PublishFor)
                </td>
                <td>
                    @*@Html.LabelFor(model => model.PublishStartDate, new { @style = "display: inline-block;" })
                        <label class="labelInfo"><img src="~/Content/img/info.png" /> Date when Ad started </label>
                        <br />
                        @Html.EditorFor(model => model.PublishStartDate)
                        @Html.ValidationMessageFor(model => model.PublishStartDate)*@
                </td>
                <td rowspan="3">
                    <label for="definedAdPages">Defined Ad positions</label>
                    <div class="col-sm-11">
                        <select id="definedAdPages" class="form-control">
                        </select>
                    </div>
                    <div class="col-sm-1">
                        <a href="javascript:void(0)"><i style="margin-top: 7px" class="glyphicon glyphicon-plus" onclick="addIntoPublishPage()"></i></a>
                    </div>
                    @Html.LabelFor(model => model.PublishPage, new { @style = "display: inline-block;" })
                    <label class="labelInfo"><img src="~/Content/img/info.png" /> Page where Ad will be display. Write each page on seperate line.</label>
                    <br />
                    @Html.TextAreaFor(model => model.PublishPage, new { @class = "form-control", @style = "position: absolut; width: 100%; height: 275px;resize: none;" })
                    @Html.ValidationMessageFor(model => model.PublishPage)
                </td>
                <td rowspan="3">
                    @Html.LabelFor(model => model.Message, new { @style = "display: inline-block;" })
                    <label class="labelInfo"><img src="~/Content/img/info.png" /> Email message for expire notification </label>
                    <br />
                    @Html.TextAreaFor(model => model.Message, new { @class = "wysiwyg hide" })
                    @*@Html.TextAreaFor(model => model.Message, new { @style = "position: absolut; width: 100%; height: 205px;resize: none;" })*@
                    @Html.ValidationMessageFor(model => model.Message)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.LiveDuration, new { @style = "display: inline-block;" })
                    <label class="labelInfo"><img src="~/Content/img/info.png" /> Days to live Ad </label>
                    <br />
                    @Html.EditorFor(model => model.LiveDuration)
                    @Html.ValidationMessageFor(model => model.LiveDuration)
                </td>
                <td>
                    @Html.LabelFor(model => model.PreExpireNotification, new { @style = "display: inline-block;" })
                    <label class="labelInfo"><img src="~/Content/img/info.png" /> Days for pre-expire notification</label>
                    <br />
                    @Html.EditorFor(model => model.PreExpireNotification)
                    @Html.ValidationMessageFor(model => model.PreExpireNotification)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.NotificationTo, new { @style = "display: inline-block;" })
                    <label class="labelInfo"><img src="~/Content/img/info.png" /> Email to send expire Ad notification </label>
                    <br />
                    @Html.EditorFor(model => model.NotificationTo)
                    @Html.ValidationMessageFor(model => model.NotificationTo)
                </td>
                <td>
                    @Html.LabelFor(model => model.ImageUrl, new { @style = "display: inline-block;" })
                    <label class="labelInfo"><img src="~/Content/img/info.png" /> Image for Ad </label>
                    <br />
                    <input type="file" name="Image" />
                    <br />
                    @Html.TextBoxFor(model => model.ImageUrl, new { @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.ImageUrl)
                </td>
            </tr>
        </table>
    }
</div>
@section Scripts{
    <script type="text/javascript">

        publishPages = [
            { text: "Select banner page", value: "none"},
            { text: "Job Seeker Home, right, vertical Ad", value: "Job Seeker Home, right, vertical Ad" },
            { text: "Job Seeker Home, left, vertical Ad", value: "Job Seeker Home, left, vertical Ad" },
            { text: "Employer Home, vertical Ad", value: "Employer Home, vertical Ad" },
            { text: "JobFairs, vertical Ad", value: "JobFairs, vertical Ad" },
            { text: "Transition News, vetical Ad", value: "Transition News, vetical Ad" },
        ];
        $(document).ready(function () {
            $("input").addClass('form-control');
            $.each(publishPages, function (index, item) {
                $('#definedAdPages').append(
                    '<option value="' + item.value + '" data-id="' + index + '">' + item.text + '</option>'
                    );
            })
            
        });
        $(function () {
            $("#ImageUrl").val("");
            $("[name=Image]").change(function () {
                $("#ImageUrl").val($(this).val());
            });
        });

        function submitForm() {
            $("form")[0].submit();
        };

        function addIntoPublishPage() {
            var temp = $('#definedAdPages option:Selected').data("id");
            if (temp != "0" && $('#PublishPage').val().indexOf(publishPages[temp].text)<0)
                $('#PublishPage').append("\n" + publishPages[temp].text);
        }
        function addStaticPage() {
            if ($('#PublishPage').val().indexOf($("#staticpage").val()) < 0)
                $("#PublishPage").html($("#PublishPage").html() + "\n" + $("#staticpage").val());
        }
    </script>
}

Phobos/Phobos/Areas/admin/Views/AdManager/Delete.cshtml
@model CivilianJobs.Models.Ad
@{
    ViewBag.Title = "Delete " + Model.Title;
}
<div class="span12 pad-left pad-right admin">
    <h2>@ViewBag.Title</h2>
    
    <h3>Are you sure you want to delete this ad?</h3>
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.AdID)
        @Html.AntiForgeryToken()
        <div class="btn-group">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-primary" })
        </div>
    }
</div>

Phobos/Phobos/Areas/admin/Views/AdManager/Edit.cshtml
@model CivilianJobs.Models.Ad
@{
    ViewBag.Title = "Edit Ad";
}
<style>
    iframe{
        max-height: 125px;
    }
</style>
<div class="span12 pad-left pad-right admin">
        <h5 class="alert-danger">@ViewBag.UserAlerts</h5>
        <h2>@ViewBag.Title</h2>
        @using (Html.BeginForm("Edit", "AdManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.AdID)
            @Html.HiddenFor(model => model.CreateDate)
            @Html.HiddenFor(model => model.NotificationSent)
            <table class="table table-bordered">
                <tr>
                    <th colspan="1">
                        <div class="btn-group">
                            <a href="javascript:void(0)" onclick="submitForm()" class="btn btn-primary">Save</a>
                            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-primary" })
                        </div>
                    </th>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.Title, new { @style = "display: inline-block;" }) 
                        <label class="labelInfo"><img src="~/Content/img/info.png"/> Will be dispalyed under Ad </label>
                        <br />
                        @Html.EditorFor(model => model.Title)
                        @Html.ValidationMessageFor(model => model.Title)
                    </td>
                    <td>
                        @Html.LabelFor(model => model.Hyperlink, new { @style = "display: inline-block;" })
                        <label class="labelInfo"><img src="~/Content/img/info.png" /> Url for Ad </label>
                        <br />
                        @Html.EditorFor(model => model.Hyperlink)
                        @Html.ValidationMessageFor(model => model.Hyperlink)
                    </td>
                    <td>

                        <label for="Hyperlink" style="display: inline-block;">Static Pages</label>
                        <label class="labelInfo"><img src="/Content/img/info.png"> List of static pages to post ad </label>
                        <br>
                        <div class="col-sm-11">
                            <select id="staticpage" class="form-control">
                                <option value="http://stage11.atomicdesign.net/page/employers">http://stage11.atomicdesign.net/page/employers</option>
                                <option value="http://stage11.atomicdesign.net/page/microsites">http://stage11.atomicdesign.net/page/microsites</option>
                                <option value="http://stage11.atomicdesign.net/page/military-job-fairs">http://stage11.atomicdesign.net/page/military-job-fairs</option>
                                <option value="http://stage11.atomicdesign.net/page/privacy-policy">http://stage11.atomicdesign.net/page/privacy-policy</option>
                                <option value="http://stage11.atomicdesign.net/staffing-products">http://stage11.atomicdesign.net/staffing-products</option>
                                <option value="http://stage11.atomicdesign.net/jobseeker/index">http://stage11.atomicdesign.net/jobseeker/index</option>
                                <option value="http://stage11.atomicdesign.net/page/about-us">http://stage11.atomicdesign.net/page/about-us</option>
                            </select>
                        </div>
                        <div class="col-sm-1">
                            <a href="javascript:void(0)"><i style="margin-top: 7px" class="glyphicon glyphicon-plus"  onclick="addStaticPage()"></i></a>
                        </div>
</td>
                    <td>
                        @Html.LabelFor(model => model.Subject, new { @style = "display: inline-block;" })
                        <label class="labelInfo"><img src="~/Content/img/info.png" /> Subject for email notification </label>
                        <br />
                        @Html.EditorFor(model => model.Subject)
                        @Html.ValidationMessageFor(model => model.Subject)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.PublishFor, new { @style = "display: inline-block;" })
                        <label class="labelInfo"><img src="~/Content/img/info.png" /> Username where Ad will be displayed. @*If left empty, it will display for every Publish Page url*@ </label>
                        <br />
                        @Html.EditorFor(model => model.PublishFor)
                        @Html.ValidationMessageFor(model => model.PublishFor)
                    </td>
                    <td>
                        @Html.LabelFor(model => model.PublishStartDate, new { @style = "display: inline-block;" })
                        <label class="labelInfo"><img src="~/Content/img/info.png" /> Date when Ad started </label>
                        <br />
                        @Html.EditorFor(model => model.PublishStartDate)
                        @Html.ValidationMessageFor(model => model.PublishStartDate)
                    </td>
                    <td rowspan="3">
                        <label for="definedAdPages">Defined Ad positions</label>
                        <div class="col-sm-11">
                            <select id="definedAdPages" class="form-control">
                            </select>
                        </div>
                        <div class="col-sm-1">
                            <a href="javascript:void(0)"><i style="margin-top: 7px" class="glyphicon glyphicon-plus" onclick="addDefinedPage()"></i></a>
                        </div>
                        @Html.LabelFor(model => model.PublishPage, new { @style = "display: inline-block;" })
                        <label class="labelInfo"><img src="~/Content/img/info.png" /> Page where Ad will be display. Write each page on seperate line.</label>
                        <br />
                        @Html.TextAreaFor(model => model.PublishPage, new { @class="form-control", @style = "position: absolut; width: 100%; height: 210px;resize: none;" })
                        @Html.ValidationMessageFor(model => model.PublishPage)
                    </td>
                    <td rowspan="3">
                        @Html.LabelFor(model => model.Message, new { @style = "display: inline-block;" })
                        <label class="labelInfo"><img src="~/Content/img/info.png" /> Email message for expire notification </label>
                        <br />
                        @Html.TextAreaFor(model => model.Message, new { @class = "wysiwyg hide" })
                        @*@Html.TextAreaFor(model => model.Message, new { @style = "position: absolut; width: 100%; height: 205px;resize: none;" })*@
                        @Html.ValidationMessageFor(model => model.Message)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.LiveDuration, new { @style = "display: inline-block;" })
                        <label class="labelInfo"><img src="~/Content/img/info.png" /> Days to live Ad </label>
                        <br />
                        @Html.EditorFor(model => model.LiveDuration)
                        @Html.ValidationMessageFor(model => model.LiveDuration)
                    </td>
                    <td>
                        @Html.LabelFor(model => model.PreExpireNotification, new { @style = "display: inline-block;" })
                        <label class="labelInfo"><img src="~/Content/img/info.png" /> Days for pre-expire notification</label>
                        <br />
                        @Html.EditorFor(model => model.PreExpireNotification)
                        @Html.ValidationMessageFor(model => model.PreExpireNotification)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.NotificationTo, new { @style = "display: inline-block;" })
                        <label class="labelInfo"><img src="~/Content/img/info.png" /> Email to send expire Ad notification </label>
                        <br />
                        @Html.EditorFor(model => model.NotificationTo)
                        @Html.ValidationMessageFor(model => model.NotificationTo)
                    </td>
                    <td>
                        @Html.LabelFor(model => model.ImageUrl, new { @style = "display: inline-block;" })
                        <label class="labelInfo"><img src="~/Content/img/info.png" /> Image for Ad </label>
                        <br />
                        <input type="file" name="Image" />
                        <br />
                        @Html.TextBoxFor(model => model.ImageUrl, new { @readonly = "readonly" })
                        @Html.ValidationMessageFor(model => model.ImageUrl)
                    </td>
                </tr>
            </table>
        }
    </div>
@section Scripts{
    <script type="text/javascript">
        publishPages = [
           { text: "Select banner page", value: "none" },
           { text: "Job Seeker Home, right, vertical Ad", value: "Job Seeker Home, right, vertical Ad" },
           { text: "Job Seeker Home, left, vertical Ad", value: "Job Seeker Home, left, vertical Ad" },
           { text: "Employer Home, vertical Ad", value: "Employer Home, vertical Ad" },
           { text: "JobFairs, vertical Ad", value: "JobFairs, vertical Ad" },
           { text: "Transition News, vetical Ad", value: "Transition News, vetical Ad" },
        ];
        $(function(){
            $("[name=Image]").change(function () {
                $("#ImageUrl").val($(this).val());
            });
        });
        function addStaticPage()
        {
            if ($('#PublishPage').val().indexOf($("#staticpage").val()) < 0)
            $("#PublishPage").html($("#PublishPage").html() + "\n" + $("#staticpage").val());
        }

        $(document).ready(function () {
            $("input").addClass('form-control');
            $.each(publishPages, function (index, item) {
                $('#definedAdPages').append(
                    '<option value="' + item.value + '" data-id="' + index + '">' + item.text + '</option>'
                    );
            })

        });

        function submitForm() {
            $("form")[0].submit();
        };

        function addDefinedPage() {
            var temp = $('#definedAdPages option:Selected').data("id");
            if (temp != "0" && $('#PublishPage').val().indexOf(publishPages[temp].text) < 0)
                $('#PublishPage').append("\n" + publishPages[temp].text);
        }

    </script>

}

Phobos/Phobos/Areas/admin/Views/AdManager/Index.cshtml
@model IEnumerable<CivilianJobs.Models.Ad>
@{
    ViewBag.Title = "Ad Management";
}
<style>
    table.vmiddle tr td {
        vertical-align: middle;
    }
</style>
<div class="span12 pad-left pad-right admin">
    <h2>@ViewBag.Title</h2>
    <p>
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
        <label style="font-weight: normal">* If <strong>Publish For </strong> is set to blank then ad will be for everybody.</label>
    </p>
    <table class="table table-striped table-bordered vmiddle">
        <tr>
            <th>
                Image
            </th>
            <th>
                Hyperlink
            </th>
            <th>
                Title
            </th>
            <th>
                Publish For
            </th>
            @*<th>
                Publish Page
            </th>*@
            <th>
                Publish Start Date
            </th>
            <th>
                Run For (Days)
            </th>
            @*<th>
                Pre-expire Notification (Days)
            </th>*@
            <th>
                Remaining (Days)
            </th>
            <th>
                Notification To
            </th>
            <th>
                Notification Sent
            </th>
            <th class="options"></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="@Html.DisplayFor(modelItem => item.ImageUrl)" height="100" width="100" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hyperlink)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublishFor)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.PublishPage)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.PublishStartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LiveDuration)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PreExpireNotification)
                </td>
                @*<td>
                    @(item.LiveDuration - item.PreExpireNotification)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.NotificationTo)
                </td>
                <td>
                    @Html.CheckBox("NotificationSent", (item.NotificationSent > 0) ? true : false, new { @disabled = "disabled" })
                </td>
                <td class="text-center">
                    <div class="btn-group">
                        @Html.ActionLink("View/Edit", "Edit", new { id = item.AdID }, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Delete", "Delete", new { id = item.AdID}, new { @class = "btn btn-danger" })
                    </div>
                </td>
            </tr>
        }
    </table>
</div>